Vagrant.configure("2") do |config|
  # Global provisioning script (if needed)
  # config.vm.provision "shell", inline: "Vagrant Initialized"  # Remove or comment out if not needed

  config.vm.define "ansible_host" do |ansible_host|
    ansible_host.vm.box = "generic/ubuntu2204"
    ansible_host.vm.network "private_network", ip: "192.168.54.151"
    ansible_host.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = 2
    end
    ansible_host.vm.provision "shell", inline: <<-SHELL
      sudo apt update
	
    SHELL
  end

  config.vm.define "web1_demo_com" do |web1_demo_com|
    web1_demo_com.vm.box = "generic/ubuntu2204"
    web1_demo_com.vm.network "private_network", ip: "192.168.54.152"

    web1_demo_com.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
    SHELL
  end
    config.vm.define "centos_remote" do |centos_remote|
    centos_remote.vm.box = "generic/centos8"
    centos_remote.vm.network "private_network", ip: "192.168.54.25"
    centos_remote.vm.provision "shell", inline: <<-SHELL
      sudo yum update
	
    SHELL
  end
end
